-- Nucleus 0.1 --
-- mods/material/ --

shape.register_blocks3("material:brick")
shape.register_blocks3("material:stone_brick")
shape.register_blocks3("material:desert_stone_brick")
shape.register_blocks3("material:sandstone_brick")
shape.register_blocks3("material:basalt_brick")
shape.register_blocks3("material:bluestone_brick")
shape.register_blocks3("material:greenstone_brick")
shape.register_blocks3("material:whitestone_brick")
shape.register_blocks3("material:shingles_clay")
shape.register_blocks3("material:shingles_wood")
shape.register_blocks3("material:shingles_slate")
shape.register_blocks3("material:wood_tile")
shape.register_blocks3("material:stone_tile")
shape.register_blocks3("material:white_stone_tile")
shape.register_blocks3("material:green_stone_tile")
shape.register_blocks3("material:blue_stone_tile")
shape.register_blocks3("material:basalt_tile")
shape.register_blocks3("material:red_stone_tile")

-- stair, slab and slope only 
shape.register_blocks3("material:stone_chequer")
shape.register_blocks3("material:green_stone_chequer")
shape.register_blocks3("material:blue_stone_chequer")
shape.register_blocks3("material:basalt_chequer")
shape.register_blocks3("material:glass")
shape.register_blocks3("material:glass_obsidian")
shape.register_blocks3("plant:straw_bale")
shape.register_blocks3("material:cob")
